//-----------------------------------------------------------------------------
//  File          : func.h
//  Module        :
//  Description   : Declrartion & Defination for func.c
//  Author        : Lewis
//  Notes         :
//
// ============================================================================
// | Naming conventions                                                       |
// | ~~~~~~~~~~~~~~~~~~                                                       |
// |        Struct define : Leading T                                         |
// |         Struct/Array : Leading s                                         |
// |             Constant : Leading K                                         |
// |      Global Variable : Leading g  (variable use outside one C file)      |
// |                                                                          |
// |   BYTE( 8 Bits) size : Leading b                                         |
// |   CHAR( 8 Bits) size : Leading c                                         |
// |   WORD(16 Bits) size : Leading w                                         |
// |  DWORD(32 Bits) size : Leading d                                         |
// |    int(32 Bits) size : Leading i                                         |
// | DDWORD(64 Bits) size : Leading dd                                        |
// |              Pointer : Leading p                                         |
// |                                                                          |
// |    Function argument : Leading a                                         |
// |       Local Variable : All lower case                                    |
// |                                                                          |
// | Examples:                                                                |
// |                Array : Leading s, (sb = arrary of byte, etc)             |
// |              Pointer : Leading p, (pb = pointer of byte, etc)            |
// ============================================================================
//
//  Date          Who         Action
//  ------------  ----------- -------------------------------------------------
//  29 Sept 2008  Lewis       Initial Version.
//-----------------------------------------------------------------------------
#ifndef _FUNC_H_
#define _FUNC_H_
#include "common.h"

extern void DisplayBatch(DWORD aRecIdx);
extern void DispReversal(void);
extern void ClearReversal(void);
extern void ClearBatch();
extern void DispTransTotal(void);
extern void PrintTxnRecord(void);
extern void PrintTotals(void);
extern BOOLEAN MerchantFunc(DWORD aFuncId);
extern BOOLEAN checkTeleCarga(void);
extern int verVersionSyspack(void);
extern void showLogo(void);
extern void showMessageError(void);
extern BOOLEAN confirmarRecarga(BYTE *empresa);
extern BOOLEAN confirmarCompraStock(BYTE *aEmpresa, BYTE *aEstabl);
extern BOOLEAN procesoConsultaSaldoImp(void);
extern BOOLEAN checkMessageInit(void);
extern BOOLEAN procesoConsultaSaldoCNB(void);
extern void mostrarSaldoCnb(void);
#endif //_FUNC_H_

